snowflake:
  baseUrl: ${snowflake_base_url}
spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: ${postgres_url}
    username: ${postgres_username}
    password: ${postgres_password}
  jpa:
    hibernate:
      ddl-auto: none
okta:
  client:
    token: ${okta_token}
    org-url: ${okta_org_url}
  oauth2:
    issuer: ${okta_issuer}
    clientId: ${okta_clientId}
    clientSecret: ${okta_clientSecret}
